# Generated by Django 4.2.20 on 2025-04-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchase_requests", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaserequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("declines", "Declined"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
