# Generated by Django 4.2.20 on 2025-04-20 16:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("items", "0001_initial"),
        ("purchase_requests", "0002_purchaserequest_status"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="purchaserequest",
            unique_together={("listing", "requester", "status")},
        ),
    ]
