# Generated by Django 4.2.20 on 2026-05-03 22:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "purchase_requests",
            "0005_alter_purchaserequest_options_purchaserequest_seller",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaserequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("declined", "Declined"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
