export const theme = {
  colors: {
    background: "#FFF9F0",
    header: "#FFF9F0",
    card: "#FFFFFF",
    cardMuted: "#FBF3E8",
    input: "#FFFCF7",
    accent: "#D44F4F",
    accentMuted: "#BF3E3E",
    accentSoft: "#F8DADA",
    accentContrast: "#FFF9F0",
    border: "#E8D8C8",
    textPrimary: "#2F2523",
    textSecondary: "#6F625B",
    icon: "#BF3E3E",
    success: "#2F855A",
    successSoft: "#DDF3E7",
    warning: "#C27A1A",
    dangerSoft: "#FCE8E8",
    disabled: "#B8AEA5",
    overlay: "rgba(47, 37, 35, 0.45)",
  },
};
