# Generated by Django 5.1.7 on 2025-04-07 02:11

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Migration Class
    Separated input fields for otpauth and userprofile. This one is the otpauth's input.
    The two different packages require different migration input, so despite the same
    name, they were separated.
    """

    initial = True

    dependencies = []

    operations = [
        # This part is different to each other. For userprofile and otpauth.
        migrations.CreateModel(
            name="OTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("otp", models.CharField(max_length=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
            ],
        ),
    ]
