# Generated by Django 4.2.20 on 2026-05-03 22:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0002_itemimage_listing_additional_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
