from django.apps import AppConfig

"""
PurchaseRequestsConfig class
Generated by Django, it initializes the API with the base configuration.
"""


class PurchaseRequestsConfig(AppConfig):
    default_auto_field = "django.db.models.BigAutoField"
    name = "purchase_requests"
